apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: terraform-provider
spec:
  package: xpkg.upbound.io/upbound/provider-terraform:v0.6.0
---
apiVersion: tf.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.cluster_name }}-providerconfig
  namespace: default
spec:
  configuration: |
    terraform {
      required_providers {
        nutanix = {
          source  = "nutanix/nutanix"
        }
      }
      backend "kubernetes" {
        secret_suffix     = "terraform"
        namespace         = "default"
        in_cluster_config = true
      }
    }

    provider "nutanix" {
      username     = "{{ .Values.user }}"
      password     = "{{ .Values.password }}"
      endpoint     = "{{ .Values.prism_central_ip }}"
      insecure     = true
      wait_timeout = 60
    }